// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hiCBnjRPs38Bu-ScCAYJ0BbBGeTc3Pc',
    appId: '1:710984482731:web:7d509e9377afe189849cee',
    messagingSenderId: '710984482731',
    projectId: 'fatech-c4a64',
    authDomain: 'fatech-c4a64.firebaseapp.com',
    storageBucket: 'fatech-c4a64.appspot.com',
    measurementId: 'G-D4NH7W272F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7VMzp-q19Z87-XaQOBqdIicMr4kpfg7Q',
    appId: '1:710984482731:ios:404274efa929dde5849cee',
    messagingSenderId: '710984482731',
    projectId: 'fatech-c4a64',
    storageBucket: 'fatech-c4a64.appspot.com',
    iosBundleId: 'com.example.fasolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7VMzp-q19Z87-XaQOBqdIicMr4kpfg7Q',
    appId: '1:710984482731:ios:404274efa929dde5849cee',
    messagingSenderId: '710984482731',
    projectId: 'fatech-c4a64',
    storageBucket: 'fatech-c4a64.appspot.com',
    iosBundleId: 'com.example.fasolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hiCBnjRPs38Bu-ScCAYJ0BbBGeTc3Pc',
    appId: '1:710984482731:web:5171e919277405f7849cee',
    messagingSenderId: '710984482731',
    projectId: 'fatech-c4a64',
    authDomain: 'fatech-c4a64.firebaseapp.com',
    storageBucket: 'fatech-c4a64.appspot.com',
    measurementId: 'G-2EE159HEG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ySEHZKuunwrE2tnI8n0AYRY7R7LbIdM',
    appId: '1:710984482731:android:8573f0c122938c0d849cee',
    messagingSenderId: '710984482731',
    projectId: 'fatech-c4a64',
    storageBucket: 'fatech-c4a64.appspot.com',
  );
}
